export default [
	{
		id: 1,
		address: "123 Yonge St",
		type: "Public restroom",
		location: "Nearby park",
		hours: "8am-10pm",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 5,
		location_id: 1,
		likes: 8,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 2,
		address: "456 Bay St",
		type: "Office restroom",
		location: "Corporate building",
		hours: "9am-5pm",
		public_access: false,
		wheelchair_accessible: true,
		cleanliness: 3,
		location_id: 2,
		likes: 3,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 3,
		address: "789 Queen St W",
		type: "Coffee shop restroom",
		location: "Busy cafe",
		hours: "7am-11pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 4,
		location_id: 3,
		likes: 12,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 4,
		address: "101 Front St E",
		type: "Hotel restroom",
		location: "Luxury hotel",
		hours: "24 hours",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 5,
		location_id: 4,
		likes: 6,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 5,
		address: "222 Bloor St W",
		type: "University restroom",
		location: "College campus",
		hours: "6am-12am",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 3,
		location_id: 5,
		likes: 5,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 6,
		address: "333 Dundas St E",
		type: "Mall restroom",
		location: "Shopping center",
		hours: "9am-9pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 4,
		location_id: 6,
		likes: 9,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 7,
		address: "444 College St",
		type: "Bar restroom",
		location: "Nightlife venue",
		hours: "5pm-2am",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 2,
		location_id: 7,
		likes: 2,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 8,
		address: "555 King St W",
		type: "Restaurant restroom",
		location: "Dining establishment",
		hours: "11am-11pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 4,
		location_id: 8,
		likes: 7,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 9,
		address: "666 Spadina Ave",
		type: "Library restroom",
		location: "Public library",
		hours: "10am-8pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 5,
		location_id: 9,
		likes: 10,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 10,
		address: "777 Eglinton Ave E",
		type: "Gas station restroom",
		location: "Highway stop",
		hours: "24 hours",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 3,
		location_id: 10,
		likes: 4,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 11,
		address: "888 Lawrence Ave W",
		type: "Office building restroom",
		location: "Business district",
		hours: "8am-6pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 4,
		location_id: 11,
		likes: 6,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 12,
		address: "999 St Clair Ave W",
		type: "School restroom",
		location: "Elementary school",
		hours: "8am-4pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 5,
		location_id: 12,
		likes: 8,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 13,
		address: "111 Bloor St E",
		type: "Cinema restroom",
		location: "Movie theater",
		hours: "12pm-12am",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 3,
		location_id: 13,
		likes: 7,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 14,
		address: "222 King St E",
		type: "Store restroom",
		location: "Shopping district",
		hours: "10am-6pm",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 4,
		location_id: 14,
		likes: 9,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 15,
		address: "333 Queen St E",
		type: "Office building restroom",
		location: "Corporate office",
		hours: "9am-7pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 5,
		location_id: 15,
		likes: 5,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 16,
		address: "444 Bloor St W",
		type: "Coffee shop restroom",
		location: "Cafe",
		hours: "7am-9pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 4,
		location_id: 1,
		likes: 6,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 17,
		address: "555 Dundas St E",
		type: "Hotel restroom",
		location: "Hotel",
		hours: "24 hours",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 5,
		location_id: 2,
		likes: 8,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 18,
		address: "666 King St W",
		type: "Public restroom",
		location: "Park",
		hours: "8am-10pm",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 3,
		location_id: 3,
		likes: 3,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 19,
		address: "777 Queen St W",
		type: "Office restroom",
		location: "Business center",
		hours: "9am-5pm",
		public_access: false,
		wheelchair_accessible: true,
		cleanliness: 4,
		location_id: 4,
		likes: 10,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 20,
		address: "888 Front St E",
		type: "Coffee shop restroom",
		location: "Local cafe",
		hours: "7am-11pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 5,
		location_id: 5,
		likes: 4,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 21,
		address: "999 Bay St",
		type: "Hotel restroom",
		location: "Luxury hotel",
		hours: "24 hours",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 4,
		location_id: 6,
		likes: 7,
        gender_neutral: false,
        family_friendly: true,
	},
	{
		id: 22,
		address: "111 University Ave",
		type: "University restroom",
		location: "Campus",
		hours: "6am-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 7,
        likes: 12,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 23,
        address: "222 Dundas St W",
        type: "Mall restroom",
        location: "Shopping center",
        hours: "9am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 8,
        likes: 5,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 24,
        address: "333 College St",
        type: "Bar restroom",
        location: "Nightlife venue",
        hours: "5pm-2am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 2,
        location_id: 9,
        likes: 9,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 25,
        address: "444 King St W",
        type: "Restaurant restroom",
        location: "Dining establishment",
        hours: "11am-11pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 10,
        likes: 2,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 26,
        address: "555 Spadina Ave",
        type: "Library restroom",
        location: "Public library",
        hours: "10am-8pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 11,
        likes: 6,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 27,
        address: "666 Eglinton Ave E",
        type: "Gas station restroom",
        location: "Highway stop",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 12,
        likes: 8,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 28,
        address: "777 Lawrence Ave W",
        type: "Office building restroom",
        location: "Business district",
        hours: "8am-6pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 13,
        likes: 5,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 29,
        address: "888 St Clair Ave W",
        type: "School restroom",
        location: "Elementary school",
        hours: "8am-4pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 14,
        likes: 3,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 30,
        address: "999 Bloor St E",
        type: "Cinema restroom",
        location: "Movie theater",
        hours: "12pm-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 15,
        likes: 11,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 31,
        address: "111 King St E",
        type: "Store restroom",
        location: "Shopping district",
        hours: "10am-6pm",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        location_id: 1,
        likes: 7,
        gender_neutral: false,
        family_friendly: false,
    },
    {
        id: 32,
        address: "222 Queen St E",
        type: "Office building restroom",
        location: "Corporate office",
        hours: "9am-7pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 2,
        likes: 4,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 33,
        address: "333 Bloor St W",
        type: "Coffee shop restroom",
        location: "Cafe",
        hours: "7am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 3,
        likes: 9,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 34,
        address: "444 Dundas St E",
        type: "Hotel restroom",
        location: "Hotel",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 4,
        likes: 5,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 35,
        address: "555 College St",
        type: "Public restroom",
        location: "Park",
        hours: "8am-10pm",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 5,
        likes: 10,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 36,
        address: "666 King St W",
        type: "Office restroom",
        location: "Business center",
        hours: "9am-5pm",
        public_access: false,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 6,
        likes: 8,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 37,
        address: "777 Front St E",
        type: "Coffee shop restroom",
        location: "Local cafe",
        hours: "7am-11pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 7,
        likes: 2,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 38,
        address: "888 Bay St",
        type: "Hotel restroom",
        location: "Luxury hotel",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 8,
        likes: 6,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 39,
        address: "999 University Ave",
        type: "University restroom",
        location: "Campus",
        hours: "6am-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 9,
        likes: 12,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 40,
        address: "111 Dundas St W",
        type: "Mall restroom",
        location: "Shopping center",
        hours: "9am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 10,
        likes: 5,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 41,
        address: "222 College St",
        type: "Bar restroom",
        location: "Nightlife venue",
        hours: "5pm-2am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 2,
        location_id: 11,
        likes: 9,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 42,
        address: "333 King St W",
        type: "Restaurant restroom",
        location: "Dining establishment",
        hours: "11am-11pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 12,
        likes: 7,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 43,
        address: "444 Spadina Ave",
        type: "Library restroom",
        location: "Public library",
        hours: "10am-8pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 13,
        likes: 3,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 44,
        address: "555 Eglinton Ave E",
        type: "Gas station restroom",
        location: "Highway stop",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 14,
        likes: 11,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 45,
        address: "666 Lawrence Ave W",
        type: "Office building restroom",
        location: "Business district",
        hours: "8am-6pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 15,
        likes: 6,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 46,
        address: "777 St Clair Ave W",
        type: "School restroom",
        location: "Elementary school",
        hours: "8am-4pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 1,
        likes: 8,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 47,
        address: "888 Bloor St E",
        type: "Cinema restroom",
        location: "Movie theater",
        hours: "12pm-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 2,
        likes: 4,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 48,
        address: "999 King St E",
        type: "Store restroom",
        location: "Shopping district",
        hours: "10am-6pm",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        location_id: 3,
        likes: 10,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 49,
        address: "111 Queen St E",
        type: "Office building restroom",
        location: "Corporate office",
        hours: "9am-7pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 4,
        likes: 2,
        gender_neutral: false,
        family_friendly: true,
    },
    {
        id: 50,
        address: "222 Bloor St W",
        type: "Coffee shop restroom",
        location: "Cafe",
        hours: "7am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 5,
        likes: 7,
        gender_neutral: false,
        family_friendly: true,
    },
];
