export default [
	{
		id: 1,
		address: "123 Yonge St",
		type: "Public restroom",
		location: "Nearby park",
		hours: "8am-10pm",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 5,
		// coordinates: (43.6544, longitude: -79.3807 },
		location_id: 1,
		likes: 8,
	},
	{
		id: 2,
		address: "456 Bay St",
		type: "Office restroom",
		location: "Corporate building",
		hours: "9am-5pm",
		public_access: false,
		wheelchair_accessible: true,
		cleanliness: 3,
		// coordinates: (43.6512, longitude: -79.3811 },
		location_id: 2,
		likes: 3,
	},
	{
		id: 3,
		address: "789 Queen St W",
		type: "Coffee shop restroom",
		location: "Busy cafe",
		hours: "7am-11pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 4,
		// coordinates: (43.6465, longitude: -79.4073 },
		location_id: 3,
		likes: 12,
	},
	{
		id: 4,
		address: "101 Front St E",
		type: "Hotel restroom",
		location: "Luxury hotel",
		hours: "24 hours",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 5,
		// coordinates: (43.6481, longitude: -79.3756 },
		location_id: 4,
		likes: 6,
	},
	{
		id: 5,
		address: "222 Bloor St W",
		type: "University restroom",
		location: "College campus",
		hours: "6am-12am",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 3,
		// coordinates: (43.6677, longitude: -79.3957 },
		location_id: 5,
		likes: 5,
	},
	{
		id: 6,
		address: "333 Dundas St E",
		type: "Mall restroom",
		location: "Shopping center",
		hours: "9am-9pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 4,
		// coordinates: (43.6552, longitude: -79.3807 },
		location_id: 6,
		likes: 9,
	},
	{
		id: 7,
		address: "444 College St",
		type: "Bar restroom",
		location: "Nightlife venue",
		hours: "5pm-2am",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 2,
		// coordinates: (43.6561, longitude: -79.4074 },
		location_id: 7,
		likes: 2,
	},
	{
		id: 8,
		address: "555 King St W",
		type: "Restaurant restroom",
		location: "Dining establishment",
		hours: "11am-11pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 4,
		// coordinates: (43.6456, longitude: -79.3944 },
		location_id: 8,
		likes: 7,
	},
	{
		id: 9,
		address: "666 Spadina Ave",
		type: "Library restroom",
		location: "Public library",
		hours: "10am-8pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 5,
		// coordinates: (43.6525, longitude: -79.3984 },
		location_id: 9,
		likes: 10,
	},
	{
		id: 10,
		address: "777 Eglinton Ave E",
		type: "Gas station restroom",
		location: "Highway stop",
		hours: "24 hours",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 3,
		// coordinates: (43.7072, longitude: -79.3947 },
		location_id: 10,
		likes: 4,
	},
	{
		id: 11,
		address: "888 Lawrence Ave W",
		type: "Office building restroom",
		location: "Business district",
		hours: "8am-6pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 4,
		// coordinates: (43.7178, longitude: -79.4364 },
		location_id: 11,
		likes: 6,
	},
	{
		id: 12,
		address: "999 St Clair Ave W",
		type: "School restroom",
		location: "Elementary school",
		hours: "8am-4pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 5,
		// coordinates: (43.6815, longitude: -79.4257 },
		location_id: 12,
		likes: 8,
	},
	{
		id: 13,
		address: "111 Bloor St E",
		type: "Cinema restroom",
		location: "Movie theater",
		hours: "12pm-12am",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 3,
		// coordinates: (43.6701, longitude: -79.3845 },
		location_id: 13,
		likes: 7,
	},
	{
		id: 14,
		address: "222 King St E",
		type: "Store restroom",
		location: "Shopping district",
		hours: "10am-6pm",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 4,
		// coordinates: (43.6493, longitude: -79.3716 },
		location_id: 14,
		likes: 9,
	},
	{
		id: 15,
		address: "333 Queen St E",
		type: "Office building restroom",
		location: "Corporate office",
		hours: "9am-7pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 5,
		// coordinates: (43.6549, longitude: -79.3693 },
		location_id: 15,
		likes: 5,
	},
	{
		id: 16,
		address: "444 Bloor St W",
		type: "Coffee shop restroom",
		location: "Cafe",
		hours: "7am-9pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 4,
		// coordinates: (43.6657, longitude: -79.4072 },
		location_id: 1,
		likes: 6,
	},
	{
		id: 17,
		address: "555 Dundas St E",
		type: "Hotel restroom",
		location: "Hotel",
		hours: "24 hours",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 5,
		// coordinates: (43.6568, longitude: -79.3803 },
		location_id: 2,
		likes: 8,
	},
	{
		id: 18,
		address: "666 King St W",
		type: "Public restroom",
		location: "Park",
		hours: "8am-10pm",
		public_access: true,
		wheelchair_accessible: false,
		cleanliness: 3,
		// coordinates: (43.6441, longitude: -79.3941 },
		location_id: 3,
		likes: 3,
	},
	{
		id: 19,
		address: "777 Queen St W",
		type: "Office restroom",
		location: "Business center",
		hours: "9am-5pm",
		public_access: false,
		wheelchair_accessible: true,
		cleanliness: 4,
		// coordinates: (43.6514, longitude: -79.4005 },
		location_id: 4,
		likes: 10,
	},
	{
		id: 20,
		address: "888 Front St E",
		type: "Coffee shop restroom",
		location: "Local cafe",
		hours: "7am-11pm",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 5,
		// coordinates: (43.6502, longitude: -79.3695 },
		location_id: 5,
		likes: 4,
	},
	{
		id: 21,
		address: "999 Bay St",
		type: "Hotel restroom",
		location: "Luxury hotel",
		hours: "24 hours",
		public_access: true,
		wheelchair_accessible: true,
		cleanliness: 4,
		// coordinates: (43.6606, longitude: -79.3871 },
		location_id: 6,
		likes: 7,
	},
	{
		id: 22,
		address: "111 University Ave",
		type: "University restroom",
		location: "Campus",
		hours: "6am-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        // coordinates: (43.6487, longitude: -79.3851 },
        location_id: 7,
        likes: 12,
    },
    {
        id: 23,
        address: "222 Dundas St W",
        type: "Mall restroom",
        location: "Shopping center",
        hours: "9am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        // coordinates: (43.6542, longitude: -79.3877 },
        location_id: 8,
        likes: 5,
    },
    {
        id: 24,
        address: "333 College St",
        type: "Bar restroom",
        location: "Nightlife venue",
        hours: "5pm-2am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 2,
        // coordinates: (43.6577, longitude: -79.4032 },
        location_id: 9,
        likes: 9,
    },
    {
        id: 25,
        address: "444 King St W",
        type: "Restaurant restroom",
        location: "Dining establishment",
        hours: "11am-11pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        // coordinates: (43.6458, longitude: -79.3942 },
        location_id: 10,
        likes: 2,
    },
    {
        id: 26,
        address: "555 Spadina Ave",
        type: "Library restroom",
        location: "Public library",
        hours: "10am-8pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        // coordinates: (43.6521, longitude: -79.3978 },
        location_id: 11,
        likes: 6,
    },
    {
        id: 27,
        address: "666 Eglinton Ave E",
        type: "Gas station restroom",
        location: "Highway stop",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        // coordinates: (43.7075, longitude: -79.3941 },
        location_id: 12,
        likes: 8,
    },
    {
        id: 28,
        address: "777 Lawrence Ave W",
        type: "Office building restroom",
        location: "Business district",
        hours: "8am-6pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        // coordinates: (43.7155, longitude: -79.4362 },
        location_id: 13,
        likes: 5,
    },
    {
        id: 29,
        address: "888 St Clair Ave W",
        type: "School restroom",
        location: "Elementary school",
        hours: "8am-4pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        // coordinates: (43.6831, longitude: -79.4259 },
        location_id: 14,
        likes: 3,
    },
    {
        id: 30,
        address: "999 Bloor St E",
        type: "Cinema restroom",
        location: "Movie theater",
        hours: "12pm-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        // coordinates: (43.6699, longitude: -79.3843 },
        location_id: 15,
        likes: 11,
    },
    {
        id: 31,
        address: "111 King St E",
        type: "Store restroom",
        location: "Shopping district",
        hours: "10am-6pm",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.6497, longitude: -79.3708 },
        location_id: 1,
        likes: 7,
    },
    {
        id: 32,
        address: "222 Queen St E",
        type: "Office building restroom",
        location: "Corporate office",
        hours: "9am-7pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        // coordinates: (43.6552, longitude: -79.3691 },
        location_id: 2,
        likes: 4,
    },
    {
        id: 33,
        address: "333 Bloor St W",
        type: "Coffee shop restroom",
        location: "Cafe",
        hours: "7am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        // coordinates: (43.6652, longitude: -79.4078 },
        location_id: 3,
        likes: 9,
    },
    {
        id: 34,
        address: "444 Dundas St E",
        type: "Hotel restroom",
        location: "Hotel",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        // coordinates: (43.6578, longitude: -79.3808 },
        location_id: 4,
        likes: 5,
    },
    {
        id: 35,
        address: "555 College St",
        type: "Public restroom",
        location: "Park",
        hours: "8am-10pm",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        // coordinates: (43.6442, longitude: -79.3949 },
        location_id: 5,
        likes: 10,
    },
    {
        id: 36,
        address: "666 King St W",
        type: "Office restroom",
        location: "Business center",
        hours: "9am-5pm",
        public_access: false,
        wheelchair_accessible: true,
        cleanliness: 4,
        // coordinates: (43.6517, longitude: -79.4012 },
        location_id: 6,
        likes: 8,
    },
    {
        id: 37,
        address: "777 Front St E",
        type: "Coffee shop restroom",
        location: "Local cafe",
        hours: "7am-11pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        // coordinates: (43.6501, longitude: -79.3687 },
        location_id: 7,
        likes: 2,
    },
    {
        id: 38,
        address: "888 Bay St",
        type: "Hotel restroom",
        location: "Luxury hotel",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        // coordinates: (43.6609, longitude: -79.3853 },
        location_id: 8,
        likes: 6,
    },
    {
        id: 39,
        address: "999 University Ave",
        type: "University restroom",
        location: "Campus",
        hours: "6am-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        // coordinates: (43.6482, longitude: -79.3873 },
        location_id: 9,
        likes: 12,
    },
    {
        id: 40,
        address: "111 Dundas St W",
        type: "Mall restroom",
        location: "Shopping center",
        hours: "9am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        // coordinates: (43.6541, longitude: -79.3879 },
        location_id: 10,
        likes: 5,
    },
    {
        id: 41,
        address: "222 College St",
        type: "Bar restroom",
        location: "Nightlife venue",
        hours: "5pm-2am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 2,
        // coordinates: (43.6572, longitude: -79.4028 },
        location_id: 11,
        likes: 9,
    },
    {
        id: 42,
        address: "333 King St W",
        type: "Restaurant restroom",
        location: "Dining establishment",
        hours: "11am-11pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        // coordinates: (43.6462, longitude: -79.3932 },
        location_id: 12,
        likes: 7,
    },
    {
        id: 43,
        address: "444 Spadina Ave",
        type: "Library restroom",
        location: "Public library",
        hours: "10am-8pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        // coordinates: (43.6524, longitude: -79.3972 },
        location_id: 13,
        likes: 3,
    },
    {
        id: 44,
        address: "555 Eglinton Ave E",
        type: "Gas station restroom",
        location: "Highway stop",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        // coordinates: (43.7071, longitude: -79.3937 },
        location_id: 14,
        likes: 11,
    },
    {
        id: 45,
        address: "666 Lawrence Ave W",
        type: "Office building restroom",
        location: "Business district",
        hours: "8am-6pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        // coordinates: (43.7165, longitude: -79.4375 },
        location_id: 15,
        likes: 6,
    },
    {
        id: 46,
        address: "777 St Clair Ave W",
        type: "School restroom",
        location: "Elementary school",
        hours: "8am-4pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        // coordinates: (43.6824, longitude: -79.4253 },
        location_id: 1,
        likes: 8,
    },
    {
        id: 47,
        address: "888 Bloor St E",
        type: "Cinema restroom",
        location: "Movie theater",
        hours: "12pm-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        // coordinates: (43.6702, longitude: -79.3841 },
        location_id: 2,
        likes: 4,
    },
    {
        id: 48,
        address: "999 King St E",
        type: "Store restroom",
        location: "Shopping district",
        hours: "10am-6pm",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.6507, longitude: -79.3703 },
        location_id: 3,
        likes: 10,
    },
    {
        id: 49,
        address: "111 Queen St E",
        type: "Office building restroom",
        location: "Corporate office",
        hours: "9am-7pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        // coordinates: (43.6558, longitude: -79.3692 },
        location_id: 4,
        likes: 2,
    },
    {
        id: 50,
        address: "222 Bloor St W",
        type: "Coffee shop restroom",
        location: "Cafe",
        hours: "7am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        // coordinates: (43.6659, longitude: -79.4083 },
        location_id: 5,
        likes: 7,
    },
];
