export default [
    {
        id: 1,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 1,
        likes: 4,
    },
    {
        id: 2,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 1,
        likes: 4,
    },
    {
        id: 3,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 1,
        likes: 4,
    },
    {
        id: 4,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 1,
        likes: 4,
    },
    {
        id: 5,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 2,
        likes: 4,
    },
    {
        id: 6,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 2,
        likes: 4,
    },
    {
        id: 7,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 2,
        likes: 4,
    },
    {
        id: 8,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 2,
        likes: 4,
    },
    {
        id: 9,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 2,
        likes: 4,
    },
    {
        id: 10,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 3,
        likes: 4,
    },
    {
        id: 11,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 3,
        likes: 4,
    },
    {
        id: 12,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 3,
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 4,
        likes: 4,
    },
    {
        id: 14,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 4,
        likes: 4,
    },
    {
        id: 15,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 4,
        likes: 4,
    },
    {
        id: 16,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 4,
        likes: 4,
    },
    {
        id: 17,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 5,
        likes: 4,
    },
    {
        id: 18,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 5,
        likes: 4,
    },
    {
        id: 19,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 6,
        likes: 4,
    },
    {
        id: 20,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 7,
        likes: 4,
    },
    {
        id: 21,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 7,
        likes: 4,
    },
    {
        id: 22,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 7,
        likes: 4,
    },
    {
        id: 23,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 7,
        likes: 4,
    },
    {
        id: 24,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 7,
        likes: 4,
    },
    {
        id: 25,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 7,
        likes: 4,
    },
    {
        id: 26,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 7,
        likes: 4,
    },
    {
        id: 27,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 8,
        likes: 4,
    },
    {
        id: 28,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 8,
        likes: 4,
    },
    {
        id: 29,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 8,
        likes: 4,
    },
    {
        id: 30,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 8,
        likes: 4,
    },
    {
        id: 31,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 8,
        likes: 4,
    },
    {
        id: 32,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 8,
        likes: 4,
    },
    {
        id: 33,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 8,
        likes: 4,
    },
    {
        id: 34,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 8,
        likes: 4,
    },
    {
        id: 35,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 8,
        likes: 4,
    },
    {
        id: 36,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 8,
        likes: 4,
    },
    {
        id: 37,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        // coordinates: (43.644111, -79.377023),
        location_id: 9,
        likes: 4,
    }
]