export default [
    {
        id: 1,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "1",
        likes: 4,
    },
    {
        id: 2,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "1",
        likes: 4,
    },
    {
        id: 3,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "1",
        likes: 4,
    },
    {
        id: 4,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "1",
        likes: 4,
    },
    {
        id: 5,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "2",
        likes: 4,
    },
    {
        id: 6,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "2",
        likes: 4,
    },
    {
        id: 7,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "2",
        likes: 4,
    },
    {
        id: 8,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "2",
        likes: 4,
    },
    {
        id: 9,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "2",
        likes: 4,
    },
    {
        id: 10,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "3",
        likes: 4,
    },
    {
        id: 11,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "3",
        likes: 4,
    },
    {
        id: 12,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "3",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "4",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "4",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "4",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "4",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "5",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "5",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "6",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "7",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "7",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "7",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "7",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "7",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "7",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "7",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "8",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "8",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "8",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "8",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "8",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "8",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "8",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "8",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "8",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "8",
        likes: 4,
    },
    {
        id: 13,
        address: "65 Front St W",
        type: "Washroom inside Osmows",
        location: "Northside, restaurant",
        hours: "10am-1am",
        public_access: "true",
        wheelchair_accessible: "false",
        cleanliness: "4",
        coordinates: "43.644111, -79.377023",
        location_id: "9",
        likes: 4,
    }
]